"""Add RegionalManager and link to Trader branches

Revision ID: 08c024b999fc
Revises: 47adc6afee2b
Create Date: 2025-08-21 08:23:38.457090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c024b999fc'
down_revision = '47adc6afee2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('regional_managers',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=128), nullable=False),
    # sa.Column('region', sa.String(length=64), nullable=False),
    # sa.Column('operational_cost_year', sa.Float(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airport_iata', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('other_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_costs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regional_manager_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_foreign_key('fk_traders_regional_manager_id', 'regional_managers', ['regional_manager_id'], ['id'])
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('fk_traders_regional_manager_id', type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('regional_manager_id')
        batch_op.drop_column('additional_info')
        batch_op.drop_column('other_costs')
        batch_op.drop_column('other_taxes')
        batch_op.drop_column('airport_iata')

    # op.drop_table('regional_managers')
    # ### end Alembic commands ###
