"""Add Shipment and ShipmentProduct models

Revision ID: 0ab1ea16c365
Revises: e8f58624572a
Create Date: 2025-10-13 10:30:34.204152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab1ea16c365'
down_revision = 'e8f58624572a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('route_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('aircraft_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('route_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('route_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('aircraft_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('from_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('to_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('finish_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('total_distance_nm',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_flight_time_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_adjusted_flight_time_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_gallons',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_block_hours_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_overflight_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_oew_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_fuel_weight_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_max_payload_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_no_tank_tow_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_avail_extra_fuel_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_tank_tow_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_route_aircraft_id', 'aircraft', ['aircraft_id'], ['id'])
        batch_op.create_foreign_key('fk_route_from_airport_id', 'airports', ['from_airport_id'], ['id'])
        batch_op.create_foreign_key('fk_route_to_airport_id', 'airports', ['to_airport_id'], ['id'])
        batch_op.create_foreign_key('fk_route_finish_airport_id', 'airports', ['finish_airport_id'], ['id'])

    # with op.batch_alter_table('shipment_products', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_user', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('type_of_freight', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('port_of_shipping', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('consignee_port_of_shipping', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('trading_region', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('trading_regional_manager', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('trading_country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('trading_branch', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('consignee_region', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('consignee_regional_manager', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('consignee_country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('consignee_branch', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('departure_route', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('route_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('available_payload', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_of_return', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('target_cargo_load', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('est_outb_kg_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_route', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('route_cost_return', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('available_payload_return', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_flight_cost_display', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_cargo_load_return_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('est_ret_kg_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_product_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_export_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_exporter_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fca_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fca_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cargo_load_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_air_freight_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cargo_unload_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cip_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_import_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_pr_cost_dat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_dat_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_shipment_dat_cost', sa.Float(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('second_leg_ft')
        batch_op.drop_column('first_leg_ft')
        batch_op.drop_column('selected_aircraft')
        batch_op.drop_column('second_leg_cost')
        batch_op.drop_column('first_leg_cost')
        batch_op.drop_column('second_leg_payload')
        batch_op.drop_column('second_leg_route')
        batch_op.drop_column('departure_route_id')
        batch_op.drop_column('first_leg_route')
        batch_op.drop_column('return_tcl')
        batch_op.drop_column('first_leg_payload')
        batch_op.drop_column('outbound_kg_cost')
        batch_op.drop_column('second_leg_distance')
        batch_op.drop_column('first_leg_distance')
        batch_op.drop_column('return_kg_cost')
        batch_op.drop_column('return_type')
        batch_op.drop_column('outbound_tcl')
        batch_op.drop_column('return_route_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_route_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('outbound_tcl', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('return_type', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('return_kg_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('first_leg_distance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('second_leg_distance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('outbound_kg_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('first_leg_payload', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('return_tcl', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('first_leg_route', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('departure_route_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('second_leg_route', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('second_leg_payload', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('first_leg_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('second_leg_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('selected_aircraft', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_leg_ft', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('second_leg_ft', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(None, 'routes', ['departure_route_id'], ['id'])
        batch_op.create_foreign_key(None, 'routes', ['return_route_id'], ['id'])
        batch_op.drop_column('total_shipment_dat_cost')
        batch_op.drop_column('total_dat_profit')
        batch_op.drop_column('total_pr_cost_dat')
        batch_op.drop_column('total_import_taxes')
        batch_op.drop_column('total_cip_cost')
        batch_op.drop_column('total_cargo_unload_cost')
        batch_op.drop_column('total_air_freight_cost')
        batch_op.drop_column('total_cargo_load_cost')
        batch_op.drop_column('total_fca_usd')
        batch_op.drop_column('total_fca_cost')
        batch_op.drop_column('total_exporter_profit')
        batch_op.drop_column('total_export_taxes')
        batch_op.drop_column('total_product_cost')
        batch_op.drop_column('total_weight')
        batch_op.drop_column('est_ret_kg_cost')
        batch_op.drop_column('target_cargo_load_return_percentage')
        batch_op.drop_column('total_flight_cost_display')
        batch_op.drop_column('available_payload_return')
        batch_op.drop_column('route_cost_return')
        batch_op.drop_column('return_route')
        batch_op.drop_column('est_outb_kg_cost')
        batch_op.drop_column('target_cargo_load')
        batch_op.drop_column('type_of_return')
        batch_op.drop_column('available_payload')
        batch_op.drop_column('route_cost')
        batch_op.drop_column('departure_route')
        batch_op.drop_column('consignee_branch')
        batch_op.drop_column('consignee_country')
        batch_op.drop_column('consignee_regional_manager')
        batch_op.drop_column('consignee_region')
        batch_op.drop_column('trading_branch')
        batch_op.drop_column('trading_country')
        batch_op.drop_column('trading_regional_manager')
        batch_op.drop_column('trading_region')
        batch_op.drop_column('consignee_port_of_shipping')
        batch_op.drop_column('port_of_shipping')
        batch_op.drop_column('type_of_freight')
        batch_op.drop_column('shipment_user')

    with op.batch_alter_table('shipment_products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'shipments', ['shipment_reference'], ['shipment_reference'])

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_finish_airport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_to_airport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_from_airport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_aircraft_id', type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('leg1_tank_tow_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_avail_extra_fuel_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_no_tank_tow_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_max_payload_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_fuel_weight_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_oew_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_overflight_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_block_hours_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_gallons',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_adjusted_flight_time_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_flight_time_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_distance_nm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('finish_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('to_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('from_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('aircraft_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('route_summary',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('route_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('aircraft_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('route_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
