"""Rename Country.name to Country.country_name

Revision ID: 0b5d8836b713
Revises: 921c9aa54199
Create Date: 2025-07-28 14:01:25.837344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5d8836b713'
down_revision = '921c9aa54199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=64), nullable=False))
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['country_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['country_code'])
        batch_op.alter_column('country_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('country_name')

    # ### end Alembic commands ###
