"""Rename terminal to ground_terminal and add sea_port to Trader model

Revision ID: 2657a75ec228
Revises: 70363c0bebc7
Create Date: 2025-09-01 13:03:50.783570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2657a75ec228'
down_revision = '70363c0bebc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_terminal', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sea_port', sa.String(length=64), nullable=True))
        batch_op.drop_column('terminal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('sea_port')
        batch_op.drop_column('ground_terminal')

    # ### end Alembic commands ###
