"""Add adjusted flight time columns to Route

Revision ID: 27ee903c6c55
Revises: ee4ea919de60
Create Date: 2025-08-15 18:12:37.461333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ee903c6c55'
down_revision = 'ee4ea919de60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_adjusted_flight_time_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leg1_adjusted_flight_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leg2_adjusted_flight_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('leg2_adjusted_flight_time')
        batch_op.drop_column('leg1_adjusted_flight_time')
        batch_op.drop_column('total_adjusted_flight_time_hours')

    # ### end Alembic commands ###
