"""Add type_of_freight and clarify name as port name in traders

Revision ID: 3d0cc0126fdb
Revises: da11a2f62eb0
Create Date: 2025-09-01 12:37:08.634041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0cc0126fdb'
down_revision = 'da11a2f62eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_freight', sa.String(length=64), nullable=True))
        batch_op.drop_column('other_costs')
        batch_op.drop_column('is_manager')
        batch_op.drop_column('import_other_cost')
        batch_op.drop_column('import_other_taxes')
        batch_op.drop_column('export_other_cost')
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('export_other_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_other_taxes', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_other_cost', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('is_manager', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('other_costs', sa.FLOAT(), nullable=True))
        batch_op.drop_column('type_of_freight')

    # ### end Alembic commands ###
