"""add region to country

Revision ID: 47adc6afee2b
Revises: e24fc3c3e7f4
Create Date: 2025-08-20 10:10:14.163677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47adc6afee2b'
down_revision = 'e24fc3c3e7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=32), nullable=True))

    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_column('region')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
