"""empty message

Revision ID: 503131371e04
Revises: f35ca7286961
Create Date: 2025-08-07 13:55:24.666199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503131371e04'
down_revision = 'f35ca7286961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=64), nullable=False),
    sa.Column('shipper', sa.String(length=64), nullable=False),
    sa.Column('consignee', sa.String(length=64), nullable=False),
    sa.Column('first_leg_route', sa.String(length=64), nullable=False),
    sa.Column('first_leg_distance', sa.Float(), nullable=True),
    sa.Column('first_leg_ft', sa.Float(), nullable=True),
    sa.Column('first_leg_cost', sa.Float(), nullable=True),
    sa.Column('first_leg_payload', sa.Float(), nullable=True),
    sa.Column('second_leg_route', sa.String(length=64), nullable=True),
    sa.Column('second_leg_distance', sa.Float(), nullable=True),
    sa.Column('second_leg_ft', sa.Float(), nullable=True),
    sa.Column('second_leg_cost', sa.Float(), nullable=True),
    sa.Column('second_leg_payload', sa.Float(), nullable=True),
    sa.Column('selected_aircraft', sa.String(length=64), nullable=True),
    sa.Column('return_type', sa.String(length=32), nullable=True),
    sa.Column('outbound_cost_weight', sa.Float(), nullable=True),
    sa.Column('outbound_tcl', sa.Float(), nullable=True),
    sa.Column('outbound_kg_cost', sa.Float(), nullable=True),
    sa.Column('return_cost_weight', sa.Float(), nullable=True),
    sa.Column('return_tcl', sa.Float(), nullable=True),
    sa.Column('return_kg_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_reference')
    )
    op.drop_table('aircraft')
    op.drop_table('products')
    op.drop_table('traders')
    op.drop_table('airports')
    op.drop_table('countries')
    op.drop_table('routes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('aircraft_id', sa.VARCHAR(), nullable=False),
    sa.Column('route_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('from_airport_id', sa.INTEGER(), nullable=False),
    sa.Column('to_airport_id', sa.INTEGER(), nullable=False),
    sa.Column('finish_airport_id', sa.INTEGER(), nullable=True),
    sa.Column('total_distance', sa.FLOAT(), nullable=True),
    sa.Column('total_flight_time', sa.FLOAT(), nullable=True),
    sa.Column('total_route_fuel_gls', sa.FLOAT(), nullable=True),
    sa.Column('total_bh_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('total_fuel_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('total_leg_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg1_route', sa.VARCHAR(length=128), nullable=True),
    sa.Column('leg1_distance', sa.FLOAT(), nullable=True),
    sa.Column('leg1_flight_time', sa.FLOAT(), nullable=True),
    sa.Column('leg1_route_fuel_gls', sa.FLOAT(), nullable=True),
    sa.Column('leg1_bh_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg1_fuel_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg1_total_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg1_oew_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg1_fuel_weight_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg1_max_payload_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg1_no_tank_tow_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg1_avail_extra_fuel_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg1_tank_tow_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_route', sa.VARCHAR(length=128), nullable=True),
    sa.Column('leg2_distance', sa.FLOAT(), nullable=True),
    sa.Column('leg2_flight_time', sa.FLOAT(), nullable=True),
    sa.Column('leg2_route_fuel_gls', sa.FLOAT(), nullable=True),
    sa.Column('leg2_bh_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg2_fuel_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg2_total_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('leg2_oew_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_fuel_weight_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_max_payload_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_no_tank_tow_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_avail_extra_fuel_lbs', sa.FLOAT(), nullable=True),
    sa.Column('leg2_tank_tow_lbs', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('route_summary', sa.VARCHAR(length=255), nullable=True),
    sa.Column('aircraft_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('from_airport_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('to_airport_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('finish_airport_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('total_distance_nm', sa.FLOAT(), nullable=True),
    sa.Column('total_flight_time_hours', sa.FLOAT(), nullable=True),
    sa.Column('total_fuel_gallons', sa.FLOAT(), nullable=True),
    sa.Column('total_fuel_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_block_hours_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('leg_details', sa.TEXT(), nullable=True),
    sa.Column('payload_details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['finish_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['from_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['to_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('country_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('country_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('airports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('iata_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', sa.INTEGER(), nullable=False),
    sa.Column('fuel_cost_gl', sa.FLOAT(), nullable=True),
    sa.Column('cargo_handling_cost_kg', sa.FLOAT(), nullable=True),
    sa.Column('airport_fee', sa.FLOAT(), nullable=True),
    sa.Column('turnaround_cost', sa.FLOAT(), nullable=True),
    sa.Column('other_desc', sa.VARCHAR(length=100), nullable=True),
    sa.Column('other_cost', sa.FLOAT(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('geo_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_verified_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('altitude_ft', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('traders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('export_profit_pct', sa.FLOAT(), nullable=True),
    sa.Column('export_sales_tax', sa.FLOAT(), nullable=True),
    sa.Column('export_other_taxes', sa.FLOAT(), nullable=True),
    sa.Column('import_profit_pct', sa.FLOAT(), nullable=True),
    sa.Column('import_other_taxes', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('revenue_taxes', sa.FLOAT(), nullable=True),
    sa.Column('operational_cost_year', sa.FLOAT(), nullable=True),
    sa.Column('export_other_cost', sa.FLOAT(), nullable=True),
    sa.Column('import_taxes', sa.FLOAT(), nullable=True),
    sa.Column('import_other_cost', sa.FLOAT(), nullable=True),
    sa.Column('trader_code', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_code', name=op.f('uq_trader_code'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('country_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('trade_unit', sa.INTEGER(), nullable=True),
    sa.Column('fca_cost_per_wu', sa.FLOAT(), nullable=True),
    sa.Column('packaging', sa.VARCHAR(length=64), nullable=True),
    sa.Column('packaging_weight', sa.FLOAT(), nullable=True),
    sa.Column('units_per_pack', sa.INTEGER(), nullable=True),
    sa.Column('packaging_cost', sa.FLOAT(), nullable=True),
    sa.Column('other_info', sa.TEXT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=4), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('mtow_kg', sa.FLOAT(), nullable=True),
    sa.Column('mtow_lbs', sa.FLOAT(), nullable=True),
    sa.Column('mldgw_kg', sa.FLOAT(), nullable=True),
    sa.Column('mldgw_lbs', sa.FLOAT(), nullable=True),
    sa.Column('zero_fuel_kg', sa.FLOAT(), nullable=True),
    sa.Column('zero_fuel_lbs', sa.FLOAT(), nullable=True),
    sa.Column('max_ramp_kg', sa.FLOAT(), nullable=True),
    sa.Column('max_ramp_lbs', sa.FLOAT(), nullable=True),
    sa.Column('empty_weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('empty_weight_lbs', sa.FLOAT(), nullable=True),
    sa.Column('max_payload_kg', sa.FLOAT(), nullable=True),
    sa.Column('max_payload_lbs', sa.FLOAT(), nullable=True),
    sa.Column('fuel_capacity_gal', sa.FLOAT(), nullable=True),
    sa.Column('fuel_capacity_lbs', sa.FLOAT(), nullable=True),
    sa.Column('fuel_burn_gal', sa.FLOAT(), nullable=True),
    sa.Column('fuel_burn_lbs', sa.FLOAT(), nullable=True),
    sa.Column('min_fuel_landed_gal', sa.FLOAT(), nullable=True),
    sa.Column('min_fuel_landed_lbs', sa.FLOAT(), nullable=True),
    sa.Column('min_fuel_alternate_gal', sa.FLOAT(), nullable=True),
    sa.Column('min_fuel_alternate_lbs', sa.FLOAT(), nullable=True),
    sa.Column('cargo_positions_main_deck', sa.INTEGER(), nullable=True),
    sa.Column('cargo_positions_lower_deck', sa.INTEGER(), nullable=True),
    sa.Column('acmi_cost', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('cruise_speed', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shipments')
    # ### end Alembic commands ###
