"""Update trader model with new field structure

Revision ID: 5ba26d40ec72
Revises: 5d3c4af22b65
Create Date: 2025-08-04 08:35:52.580302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba26d40ec72'
down_revision = '5d3c4af22b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('revenue_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('operational_cost_year', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('export_other_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('import_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('import_other_cost', sa.Float(), nullable=True))
        batch_op.drop_column('import_sales_tax')
        batch_op.drop_column('export_operating_expenses_pct')
        batch_op.drop_column('import_operating_expenses_pct')
        batch_op.drop_column('import_year_operating_costs')
        batch_op.drop_column('export_year_operating_costs')
        batch_op.drop_column('import_import_taxes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_import_taxes', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('export_year_operating_costs', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_year_operating_costs', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_operating_expenses_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('export_operating_expenses_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('import_sales_tax', sa.FLOAT(), nullable=True))
        batch_op.drop_column('import_other_cost')
        batch_op.drop_column('import_taxes')
        batch_op.drop_column('export_other_cost')
        batch_op.drop_column('operational_cost_year')
        batch_op.drop_column('revenue_taxes')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
