"""Add additional fields to Route model for enhanced saving

Revision ID: 5d3c4af22b65
Revises: e56a910f3407
Create Date: 2025-08-03 07:35:37.831723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3c4af22b65'
down_revision = 'e56a910f3407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aircraft_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('from_airport_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('to_airport_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('finish_airport_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_distance_nm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_flight_time_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fuel_gallons', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_fuel_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_block_hours_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leg_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payload_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_column('payload_details')
        batch_op.drop_column('leg_details')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('total_block_hours_cost')
        batch_op.drop_column('total_fuel_cost')
        batch_op.drop_column('total_fuel_gallons')
        batch_op.drop_column('total_flight_time_hours')
        batch_op.drop_column('total_distance_nm')
        batch_op.drop_column('finish_airport_name')
        batch_op.drop_column('to_airport_name')
        batch_op.drop_column('from_airport_name')
        batch_op.drop_column('aircraft_name')
        batch_op.drop_column('route_summary')
    # ### end Alembic commands ###
