"""Add ground_terminal_code and port_code to traders

Revision ID: 637280525116
Revises: 2657a75ec228
Create Date: 2025-09-01 15:47:57.012197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637280525116'
down_revision = '2657a75ec228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_terminal_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('port_code', sa.String(length=64), nullable=True))
        batch_op.drop_column('sea_port')
        batch_op.drop_column('ground_terminal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_terminal', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('sea_port', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('port_code')
        batch_op.drop_column('ground_terminal_code')

    # ### end Alembic commands ###
