"""Add terminal field to Trader model

Revision ID: 70363c0bebc7
Revises: eebbd2e049ee
Create Date: 2025-09-01 12:54:47.166722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70363c0bebc7'
down_revision = 'eebbd2e049ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_column('terminal')

    # ### end Alembic commands ###
