"""Unify RegionalManager and Trader models

Revision ID: 79909bd2e027
Revises: 08c024b999fc
Create Date: 2025-08-29 17:58:46.224018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79909bd2e027'
down_revision = '08c024b999fc'
branch_labels = None
depends_on = None


def upgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       # Drop the regional_managers table if it exists
       conn = op.get_bind()
       inspector = sa.inspect(conn)
       if 'regional_managers' in inspector.get_table_names():
              op.drop_table('regional_managers')

       # Always update the traders table for new schema
       with op.batch_alter_table('traders', schema=None) as batch_op:
              # Add new columns
              batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=True))
              batch_op.add_column(sa.Column('region', sa.String(length=64), nullable=True))
              batch_op.add_column(sa.Column('manager_name', sa.String(length=128), nullable=True))
              batch_op.alter_column('country_id',
                        existing_type=sa.VARCHAR(length=10),
                        nullable=True)
              batch_op.alter_column('city',
                        existing_type=sa.VARCHAR(length=100),
                        nullable=True)
              # Drop obsolete foreign key and column if present
              table_columns = [col['name'] for col in inspector.get_columns('traders')]
              if 'regional_manager_id' in table_columns:
                     try:
                            batch_op.drop_constraint('fk_traders_regional_manager_id', type_='foreignkey')
                     except Exception:
                            pass
                     batch_op.drop_column('regional_manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regional_manager_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_traders_regional_manager_id'), 'regional_managers', ['regional_manager_id'], ['id'])
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('manager_name')
        batch_op.drop_column('region')
        batch_op.drop_column('is_manager')

    op.create_table('regional_managers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('region', sa.VARCHAR(length=64), nullable=False),
    sa.Column('operational_cost_year', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
