"""Add altitude_ft column to airports table

Revision ID: 8d07475ac20f
Revises: fd1e594f3454
Create Date: 2025-08-02 21:41:02.611463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d07475ac20f'
down_revision = 'fd1e594f3454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altitude_ft', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('altitude_ft')

    # ### end Alembic commands ###
