"""Add cargo_positions columns to aircraft

Revision ID: 90787c3ce14a
Revises: 0b5d8836b713
Create Date: 2025-07-30 18:44:27.719823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90787c3ce14a'
down_revision = '0b5d8836b713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_countries')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_positions_main_deck', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo_positions_lower_deck', sa.Integer(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('cargo_positions')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('cargo_positions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('cargo_positions_lower_deck')
        batch_op.drop_column('cargo_positions_main_deck')

    op.create_table('_alembic_tmp_countries',
    sa.Column('country_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('country_name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    # ### end Alembic commands ###
