"""Initial table creation

Revision ID: 921c9aa54199
Revises: 
Create Date: 2025-07-27 12:54:33.821552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921c9aa54199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('mtow_kg', sa.Float(), nullable=True),
    sa.Column('mtow_lbs', sa.Float(), nullable=True),
    sa.Column('mldgw_kg', sa.Float(), nullable=True),
    sa.Column('mldgw_lbs', sa.Float(), nullable=True),
    sa.Column('zero_fuel_kg', sa.Float(), nullable=True),
    sa.Column('zero_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('max_ramp_kg', sa.Float(), nullable=True),
    sa.Column('max_ramp_lbs', sa.Float(), nullable=True),
    sa.Column('empty_weight_kg', sa.Float(), nullable=True),
    sa.Column('empty_weight_lbs', sa.Float(), nullable=True),
    sa.Column('max_payload_kg', sa.Float(), nullable=True),
    sa.Column('max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('fuel_capacity_gal', sa.Float(), nullable=True),
    sa.Column('fuel_capacity_lbs', sa.Float(), nullable=True),
    sa.Column('fuel_burn_gal', sa.Float(), nullable=True),
    sa.Column('fuel_burn_lbs', sa.Float(), nullable=True),
    sa.Column('min_fuel_landed_gal', sa.Float(), nullable=True),
    sa.Column('min_fuel_landed_lbs', sa.Float(), nullable=True),
    sa.Column('min_fuel_alternate_gal', sa.Float(), nullable=True),
    sa.Column('min_fuel_alternate_lbs', sa.Float(), nullable=True),
    sa.Column('cargo_positions', sa.Integer(), nullable=True),
    sa.Column('acmi_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('currency_code', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('fuel_cost_gl', sa.Float(), nullable=True),
    sa.Column('cargo_handling_cost_kg', sa.Float(), nullable=True),
    sa.Column('airport_fee', sa.Float(), nullable=True),
    sa.Column('turnaround_cost', sa.Float(), nullable=True),
    sa.Column('other_desc', sa.String(length=100), nullable=True),
    sa.Column('other_cost', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.String(length=50), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('packaging', sa.String(length=64), nullable=True),
    sa.Column('packaging_weight', sa.Float(), nullable=True),
    sa.Column('units_per_pack', sa.Integer(), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=4), nullable=True),
    sa.Column('fca_cost_per_wu', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('airports')
    op.drop_table('countries')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
