"""add shipments table

Revision ID: a1be831d5a26
Revises: 503131371e04
Create Date: 2025-08-07 14:13:33.738766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1be831d5a26'
down_revision = '503131371e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('mtow_kg', sa.Float(), nullable=True),
    sa.Column('mtow_lbs', sa.Float(), nullable=True),
    sa.Column('mldgw_kg', sa.Float(), nullable=True),
    sa.Column('mldgw_lbs', sa.Float(), nullable=True),
    sa.Column('zero_fuel_kg', sa.Float(), nullable=True),
    sa.Column('zero_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('max_ramp_kg', sa.Float(), nullable=True),
    sa.Column('max_ramp_lbs', sa.Float(), nullable=True),
    sa.Column('empty_weight_kg', sa.Float(), nullable=True),
    sa.Column('empty_weight_lbs', sa.Float(), nullable=True),
    sa.Column('max_payload_kg', sa.Float(), nullable=True),
    sa.Column('max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('fuel_capacity_gal', sa.Float(), nullable=True),
    sa.Column('fuel_capacity_lbs', sa.Float(), nullable=True),
    sa.Column('fuel_burn_gal', sa.Float(), nullable=True),
    sa.Column('fuel_burn_lbs', sa.Float(), nullable=True),
    sa.Column('min_fuel_landed_gal', sa.Float(), nullable=True),
    sa.Column('min_fuel_landed_lbs', sa.Float(), nullable=True),
    sa.Column('min_fuel_alternate_gal', sa.Float(), nullable=True),
    sa.Column('min_fuel_alternate_lbs', sa.Float(), nullable=True),
    sa.Column('cargo_positions_main_deck', sa.Integer(), nullable=True),
    sa.Column('cargo_positions_lower_deck', sa.Integer(), nullable=True),
    sa.Column('cruise_speed', sa.Float(), nullable=True),
    sa.Column('acmi_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('currency_code', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('fuel_cost_gl', sa.Float(), nullable=True),
    sa.Column('cargo_handling_cost_kg', sa.Float(), nullable=True),
    sa.Column('airport_fee', sa.Float(), nullable=True),
    sa.Column('turnaround_cost', sa.Float(), nullable=True),
    sa.Column('other_desc', sa.String(length=100), nullable=True),
    sa.Column('other_cost', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_ft', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.String(length=50), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country_id', sa.String(length=10), nullable=True),
    sa.Column('trade_unit', sa.Integer(), nullable=True),
    sa.Column('fca_cost_per_wu', sa.Float(), nullable=True),
    sa.Column('packaging', sa.String(length=64), nullable=True),
    sa.Column('packaging_weight', sa.Float(), nullable=True),
    sa.Column('units_per_pack', sa.Integer(), nullable=True),
    sa.Column('packaging_cost', sa.Float(), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_code', sa.String(length=10), nullable=True),
    sa.Column('country_id', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('revenue_taxes', sa.Float(), nullable=True),
    sa.Column('operational_cost_year', sa.Float(), nullable=True),
    sa.Column('export_profit_pct', sa.Float(), nullable=True),
    sa.Column('export_sales_tax', sa.Float(), nullable=True),
    sa.Column('export_other_taxes', sa.Float(), nullable=True),
    sa.Column('export_other_cost', sa.Float(), nullable=True),
    sa.Column('import_profit_pct', sa.Float(), nullable=True),
    sa.Column('import_taxes', sa.Float(), nullable=True),
    sa.Column('import_other_taxes', sa.Float(), nullable=True),
    sa.Column('import_other_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_code')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=128), nullable=True),
    sa.Column('aircraft_id', sa.String(), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=False),
    sa.Column('from_airport_id', sa.Integer(), nullable=False),
    sa.Column('to_airport_id', sa.Integer(), nullable=False),
    sa.Column('finish_airport_id', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('total_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('total_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_leg_cost_usd', sa.Float(), nullable=True),
    sa.Column('route_summary', sa.String(length=255), nullable=True),
    sa.Column('aircraft_name', sa.String(length=128), nullable=True),
    sa.Column('from_airport_name', sa.String(length=255), nullable=True),
    sa.Column('to_airport_name', sa.String(length=255), nullable=True),
    sa.Column('finish_airport_name', sa.String(length=255), nullable=True),
    sa.Column('total_distance_nm', sa.Float(), nullable=True),
    sa.Column('total_flight_time_hours', sa.Float(), nullable=True),
    sa.Column('total_fuel_gallons', sa.Float(), nullable=True),
    sa.Column('total_fuel_cost', sa.Float(), nullable=True),
    sa.Column('total_block_hours_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('leg_details', sa.Text(), nullable=True),
    sa.Column('payload_details', sa.Text(), nullable=True),
    sa.Column('leg1_route', sa.String(length=128), nullable=True),
    sa.Column('leg1_distance', sa.Float(), nullable=True),
    sa.Column('leg1_flight_time', sa.Float(), nullable=True),
    sa.Column('leg1_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('leg1_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_oew_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_fuel_weight_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_no_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_avail_extra_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_route', sa.String(length=128), nullable=True),
    sa.Column('leg2_distance', sa.Float(), nullable=True),
    sa.Column('leg2_flight_time', sa.Float(), nullable=True),
    sa.Column('leg2_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('leg2_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_oew_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_fuel_weight_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_no_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_avail_extra_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['finish_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['from_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['to_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('traders')
    op.drop_table('products')
    op.drop_table('airports')
    op.drop_table('countries')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
