"""Final migration with named constraints

Revision ID: ca78769b12a6
Revises: 
Create Date: 2025-10-13 10:49:59.622852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca78769b12a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('route_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('aircraft_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('route_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('route_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('aircraft_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('from_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('to_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('finish_airport_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('total_distance_nm',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_flight_time_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_adjusted_flight_time_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_gallons',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_block_hours_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_overflight_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_oew_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_fuel_weight_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_max_payload_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_no_tank_tow_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_avail_extra_fuel_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('leg1_tank_tow_lbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_route_finish_airport_id', 'airports', ['finish_airport_id'], ['id'])
        batch_op.create_foreign_key('fk_route_from_airport_id', 'airports', ['from_airport_id'], ['id'])
        batch_op.create_foreign_key('fk_route_to_airport_id', 'airports', ['to_airport_id'], ['id'])
        batch_op.create_foreign_key('fk_route_aircraft_id', 'aircraft', ['aircraft_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_aircraft_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_to_airport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_from_airport_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_finish_airport_id', type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('leg1_tank_tow_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_avail_extra_fuel_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_no_tank_tow_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_max_payload_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_fuel_weight_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('leg1_oew_lbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_overflight_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_block_hours_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_fuel_gallons',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_adjusted_flight_time_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_flight_time_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_distance_nm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('finish_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('to_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('from_airport_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('aircraft_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('route_summary',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('route_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('aircraft_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('route_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
