"""initial clean migration

Revision ID: d72b4a040044
Revises: 
Create Date: 2025-07-31 15:36:52.885300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72b4a040044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_countries')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_positions_main_deck', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo_positions_lower_deck', sa.Integer(), nullable=True))
        batch_op.drop_column('cargo_positions')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=64), nullable=False))
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('trade_unit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packaging_cost', sa.Float(), nullable=True))
        batch_op.alter_column('country_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('packaging_cost')
        batch_op.drop_column('trade_unit')
        batch_op.drop_column('product_type')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=False))
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('country_name')

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_positions', sa.INTEGER(), nullable=True))
        batch_op.drop_column('cargo_positions_lower_deck')
        batch_op.drop_column('cargo_positions_main_deck')

    op.create_table('_alembic_tmp_countries',
    sa.Column('country_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    # ### end Alembic commands ###
