"""Add Competitive_prices_table

Revision ID: e24fc3c3e7f4
Revises: 27ee903c6c55
Create Date: 2025-08-18 16:16:32.637995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24fc3c3e7f4'
down_revision = '27ee903c6c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitive_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('price_to_compare', sa.Float(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('trade_unit',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('trade_unit',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('competitive_prices')
    # ### end Alembic commands ###
