"""Add Route model for saving route calculations and payload data

Revision ID: e56a910f3407
Revises: 8d07475ac20f
Create Date: 2025-08-02 23:40:52.547033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56a910f3407'
down_revision = '8d07475ac20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=128), nullable=True),
    sa.Column('aircraft_id', sa.String(), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=False),
    sa.Column('from_airport_id', sa.Integer(), nullable=False),
    sa.Column('to_airport_id', sa.Integer(), nullable=False),
    sa.Column('finish_airport_id', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('total_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('total_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_leg_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_route', sa.String(length=128), nullable=True),
    sa.Column('leg1_distance', sa.Float(), nullable=True),
    sa.Column('leg1_flight_time', sa.Float(), nullable=True),
    sa.Column('leg1_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('leg1_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg1_oew_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_fuel_weight_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_no_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_avail_extra_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('leg1_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_route', sa.String(length=128), nullable=True),
    sa.Column('leg2_distance', sa.Float(), nullable=True),
    sa.Column('leg2_flight_time', sa.Float(), nullable=True),
    sa.Column('leg2_route_fuel_gls', sa.Float(), nullable=True),
    sa.Column('leg2_bh_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_fuel_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('leg2_oew_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_fuel_weight_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_max_payload_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_no_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_avail_extra_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('leg2_tank_tow_lbs', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['finish_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['from_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['to_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
