"""Add is_manager field to Trader model

Revision ID: eebbd2e049ee
Revises: 3d0cc0126fdb
Create Date: 2025-09-01 12:50:52.988105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebbd2e049ee'
down_revision = '3d0cc0126fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_column('is_manager')

    # ### end Alembic commands ###
