"""Add trader_code field to traders table

Revision ID: f35ca7286961
Revises: 5ba26d40ec72
Create Date: 2025-08-04 11:02:45.249111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35ca7286961'
down_revision = '5ba26d40ec72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trader_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint('uq_trader_code', ['trader_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trader_code', type_='unique')
        batch_op.drop_column('trader_code')

    # ### end Alembic commands ###
