"""Add cruise_speed column to aircraft table

Revision ID: fd1e594f3454
Revises: 936af642f503
Create Date: 2025-08-01 21:07:54.484097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1e594f3454'
down_revision = '936af642f503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cruise_speed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_column('cruise_speed')

    # ### end Alembic commands ###
